<template>
  <div class="eight14">
    <h1>8B 14LV</h1>
    <div v-for="(difficulty, grade) in difficultyBoard" v-bind:key="grade">
      <div class="grade">
        <img class="gradeBox" :src="require(`@/assets/img/grade/${difficultyBoard.length-grade}.png`)" alt="등급">
        <div class="levelBox">
          <div class="thumbBox" v-for="thumb in difficulty" v-bind:key="thumb.id">
            <img class="sName" :src="require(`@/assets/img/thumbnails/${thumb.category}/${thumb.songName}.jpg`)" alt="썸네일">
            <img class="sLevel" :src="require(`@/assets/img/level/${thumb.songLevel}.png`)" alt="난이도">
            <img class="sBorder" :src="require(`@/assets/img/border/${thumb.category}.png`)" alt="카데고리">
            <input class="judgeBox" type="text" placeholder="-- . -- %" v-model="thumb.judgement">
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "eight14",
  data: function () {
    return {
      difficultyBoard: [
        [
          {
            id: 1,
            category: 'portable2',
            songName: 'smokyquartz',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 2,
            category: 'collaboration',
            songName: 'codenamezero',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 3,
            category: 'trilogy',
            songName: 'mindcontrol',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 4,
            category: 'portable1',
            songName: 'minimallife',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 5,
            category: 'technika3',
            songName: 'rightback',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 6,
            category: 'technika3',
            songName: 'xeus',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 7,
            category: 'technika2',
            songName: 'lacampanellanurave',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 8,
            category: 'portable1',
            songName: 'sinthelastscene',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 9,
            category: 'respect',
            songName: 'analys',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 10,
            category: 'technika3',
            songName: 'blackswan',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 11,
            category: 'respect',
            songName: 'dontdie',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 12,
            category: 'respect',
            songName: 'entertheuniverse',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 13,
            category: 'portable3',
            songName: 'goneastray',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 14,
            category: 'blacksquare',
            songName: 'graveconsequence',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 15,
            category: 'vextension',
            songName: 'neverdie',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 15,
            category: 'respect',
            songName: 'royalclown',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 16,
            category: 'technika3',
            songName: 'signalize',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 17,
            category: 'technika3',
            songName: 'supernova',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 19,
            category: 'collaboration',
            songName: 'oldgold',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 20,
            category: 'collaboration',
            songName: 'conflict',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 21,
            category: 'collaboration',
            songName: 'cyberozar',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 22,
            category: 'clazziquai',
            songName: 'darkenvy',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 23,
            category: 'technika3',
            songName: 'emblem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 24,
            category: 'vextension',
            songName: 'rememberme',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 25,
            category: 'portable2',
            songName: 'rollingontheduck',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 26,
            category: 'technika2',
            songName: 'thorextendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 27,
            category: 'collaboration',
            songName: '공성전pierreblancheyonceremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 28,
            category: 'collaboration',
            songName: 'apparition',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 29,
            category: 'portable1',
            songName: 'masai',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 30,
            category: 'portable1',
            songName: 'oblivion',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 31,
            category: 'respect',
            songName: 'theobliterator',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 32,
            category: 'portable1',
            songName: 'roadofdeath',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 33,
            category: 'collaboration',
            songName: 'blackmind',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 34,
            category: 'collaboration',
            songName: 'goodnightbadluck',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 35,
            category: 'portable1',
            songName: 'hamsin',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 36,
            category: 'vextension',
            songName: 'kensei',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 37,
            category: 'vextension',
            songName: 'lisrim',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 38,
            category: 'collaboration',
            songName: 'marrymenightmare',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 39,
            category: 'collaboration',
            songName: 'myosotis',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 40,
            category: 'portable3',
            songName: 'nbrangernonstopremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 41,
            category: 'emotional',
            songName: 'spaceofsoul',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 42,
            category: 'technika3',
            songName: 'supersonic2011',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 43,
            category: 'technika1',
            songName: 'thor',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 44,
            category: 'trilogy',
            songName: 'ventilator',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 45,
            category: 'vextension',
            songName: 'vilerequiem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 46,
            category: 'collaboration',
            songName: 'warrior',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 47,
            category: 'portable2',
            songName: '태권부리',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 48,
            category: 'portable1',
            songName: 'ai',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 49,
            category: 'respect',
            songName: 'boom',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 50,
            category: 'technika3',
            songName: 'egg',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 51,
            category: 'portable3',
            songName: 'if',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 52,
            category: 'technika1',
            songName: 'shoreline',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 53,
            category: 'collaboration',
            songName: '최종무곡',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 54,
            category: 'vextension',
            songName: 'attack',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 55,
            category: 'blacksquare',
            songName: 'beatudown',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 56,
            category: 'collaboration',
            songName: 'breakaspell',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 57,
            category: 'respect',
            songName: 'chemicalslave',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 58,
            category: 'respect',
            songName: 'danceofthedead',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 59,
            category: 'collaboration',
            songName: 'itsmywarnow',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 60,
            category: 'portable3',
            songName: 'leavemealone',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 61,
            category: 'respect',
            songName: 'risingthesonic',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 62,
            category: 'vextension',
            songName: 'wonderlot777',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 63,
            category: 'collaboration',
            songName: '부여성blossoremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 64,
            category: 'respect',
            songName: '서울여자',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 65,
            category: 'technika3',
            songName: 'alifewithyou',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 66,
            category: 'technika3',
            songName: 'angel',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 67,
            category: 'portable2',
            songName: 'getontop',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 68,
            category: 'portable3',
            songName: 'masaielectrohousemix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 69,
            category: 'technika1',
            songName: 'melody',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 70,
            category: 'respect',
            songName: 'popstars',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 71,
            category: 'respect',
            songName: 'sohappy',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 72,
            category: 'trilogy',
            songName: 'yocreoquesilivehouseversion',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 73,
            category: 'respect',
            songName: 'glorydaymintormentremix',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 74,
            category: 'collaboration',
            songName: 'lesparfumsdelamour',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 75,
            category: 'collaboration',
            songName: '전설이시작된곳voidroverremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 76,
            category: 'collaboration',
            songName: '카트라이더mashuppure100remix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 77,
            category: 'portable1',
            songName: 'blythe',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 78,
            category: 'portable1',
            songName: 'oblivionrockinnightstyle',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 79,
            category: 'portable3',
            songName: 'outlawreborn',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 80,
            category: 'clazziquai',
            songName: 'creator',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 81,
            category: 'portable1',
            songName: 'enemystorm',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 82,
            category: 'portable1',
            songName: 'futurism',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 83,
            category: 'clazziquai',
            songName: 'hereinthemomentextendedmix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 84,
            category: 'portable2',
            songName: 'midnightblood',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 85,
            category: 'portable1',
            songName: 'neversay',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 86,
            category: 'collaboration',
            songName: 'ninepointeight',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 87,
            category: 'portable2',
            songName: 'squeeze',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 88,
            category: 'respect',
            songName: 'toktoktok',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 89,
            category: 'vextension',
            songName: 'welcometothespacefeatjisun',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 88,
            category: 'trilogy',
            songName: 'zet',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 89,
            category: 'collaboration',
            songName: '광명의루루라바다',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 90,
            category: 'vextension',
            songName: 'blackgold',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 91,
            category: 'portable1',
            songName: 'enemystorm',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 92,
            category: 'technika3',
            songName: 'feelmabeat',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 93,
            category: 'vextension',
            songName: 'fightnightfeatcalyae',
            songLevel: 'mx',
            judgement: '',
          },
        ],
        [
          {
            id: 94,
            category: 'portable1',
            songName: '바람에게부탁해livemix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 95,
            category: 'portable1',
            songName: 'cnp',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 96,
            category: 'collaboration',
            songName: 'grooveprayer',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 97,
            category: 'clazziquai',
            songName: 'hereinthemoment',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 98,
            category: 'portable1',
            songName: 'rayofilluminati',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 99,
            category: 'portable2',
            songName: 'showtime',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 100,
            category: 'clazziquai',
            songName: 'theclearbluesky',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 101,
            category: 'clazziquai',
            songName: 'coastaltempo',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 102,
            category: 'respect',
            songName: 'getjinxed',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 103,
            category: 'clazziquai',
            songName: 'lovercestyle',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 104,
            category: 'portable2',
            songName: 'syriana',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 105,
            category: 'trilogy',
            songName: 'yourownmiraclediscohousemix',
            songLevel: 'sc',
            judgement: '',
          },
        ]
      ]
    }
  }
}
</script>

<style scoped>

</style>