<template>
  <div class="eight13">
    <h1>8B 13LV</h1>
    <div v-for="(difficulty, grade) in difficultyBoard" v-bind:key="grade">
      <div class="grade">
        <img class="gradeBox" :src="require(`@/assets/img/grade/${difficultyBoard.length-grade}.png`)" alt="등급">
        <div class="levelBox">
          <div class="thumbBox" v-for="thumb in difficulty" v-bind:key="thumb.id">
            <img class="sName" :src="require(`@/assets/img/thumbnails/${thumb.category}/${thumb.songName}.jpg`)" alt="썸네일">
            <img class="sLevel" :src="require(`@/assets/img/level/${thumb.songLevel}.png`)" alt="난이도">
            <img class="sBorder" :src="require(`@/assets/img/border/${thumb.category}.png`)" alt="카데고리">
            <input class="judgeBox" type="text" placeholder="-- . -- %" v-model="thumb.judgement">
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "eight13",
  data: function (){
    return{
      difficultyBoard:[
        [
          {
            id: 1,
            category: 'portable2',
            songName: 'brainstorm',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 2,
            category: 'respect',
            songName: 'killerbee',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 3,
            category: 'portable2',
            songName: '태권부리',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 4,
            category: 'blacksquare',
            songName: 'cyphergate',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 5,
            category: 'technika1',
            songName: 'hexad',
            songLevel: 'mx',
            judgement: '',
          },
        ],
        [
          {
            id: 6,
            category: 'technika3',
            songName: 'overtherainbow',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 7,
            category: 'respect',
            songName: 'runaway',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 8,
            category: 'portable3',
            songName: 'therainmaker',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 9,
            category: 'technika3',
            songName: 'darkprism',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 10,
            category: 'respect',
            songName: 'glorydayjhsremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 11,
            category: 'collaboration',
            songName: 'helix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 12,
            category: 'portable2',
            songName: 'higher',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 13,
            category: 'vextension',
            songName: 'nanairo',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 15,
            category: 'respect',
            songName: 'remainsofdoom',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 16,
            category: 'technika1',
            songName: 'supersonic',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 17,
            category: 'portable2',
            songName: 'whiteblue',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 18,
            category: 'blacksquare',
            songName: '고백꽃늑대part2',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 19,
            category: 'collaboration',
            songName: 'ikazuchi',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 20,
            category: 'portable1',
            songName: 'lemonade',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 21,
            category: 'portable2',
            songName: 'nbrangersreturns',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 22,
            category: 'collaboration',
            songName: 'raytuning',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 23,
            category: 'emotional',
            songName: 'realoverdrive',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 24,
            category: 'portable1',
            songName: 'triplezoe',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 25,
            category: 'portable1',
            songName: '바람에게부탁해livemix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 26,
            category: 'technika3',
            songName: 'ad2222extendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 27,
            category: 'technika2',
            songName: 'airwave',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 28,
            category: 'technika2',
            songName: 'beeutiful',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 29,
            category: 'blacksquare',
            songName: 'keystotheworld',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 30,
            category: 'collaboration',
            songName: 'marionette',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 31,
            category: 'technika3',
            songName: 'outofctrl',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 32,
            category: 'portable3',
            songName: 'supersonicmrfunkydirtyplanetremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 33,
            category: 'portable2',
            songName: 'yourownmiracle',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 34,
            category: 'trilogy',
            songName: 'zet',
            songLevel: 'mx',
            judgement: '',
          },
        ],
        [
          {
            id: 35,
            category: 'portable1',
            songName: 'dreadnought',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 36,
            category: 'portable2',
            songName: 'seeker',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 37,
            category: 'respect',
            songName: 'binaryworld',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 38,
            category: 'technika2',
            songName: 'dualstrikers',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 39,
            category: 'clazziquai',
            songName: 'flea',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 40,
            category: 'respect',
            songName: 'gridsystem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 41,
            category: 'technika2',
            songName: 'lacampanellanurave',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 42,
            category: 'collaboration',
            songName: 'oldgold',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 43,
            category: 'collaboration',
            songName: 'theraindropflowerjamjamremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 44,
            category: 'portable3',
            songName: 'zetmrfunkyremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 45,
            category: 'portable1',
            songName: 'ftr',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 46,
            category: 'respect',
            songName: 'iwantyou반짝반짝sunshine',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 47,
            category: 'portable3',
            songName: 'mellowdfantasy',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 48,
            category: 'technika3',
            songName: 'eggextendedmix',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 49,
            category: 'collaboration',
            songName: 'thewheeltotheright',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 50,
            category: 'collaboration',
            songName: 'trrricksters',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 51,
            category: 'respect',
            songName: 'wereallgonnadie',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 52,
            category: 'blacksquare',
            songName: 'airwaveextendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 53,
            category: 'technika3',
            songName: 'egg',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 54,
            category: 'clazziquai',
            songName: 'electronics',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 55,
            category: 'collaboration',
            songName: 'magnolia',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 56,
            category: 'portable2',
            songName: 'miles',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 57,
            category: 'respect',
            songName: 'quixotic',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 58,
            category: 'collaboration',
            songName: 'satisfiction',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 59,
            category: 'technika3',
            songName: 'showdown',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 60,
            category: 'clazziquai',
            songName: 'theclearbluesky',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 61,
            category: 'technika2',
            songName: 'theguilty',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 62,
            category: 'emotional',
            songName: 'urbannight',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 63,
            category: 'clazziquai',
            songName: 'fate',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 64,
            category: 'technika2',
            songName: 'putemup',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 65,
            category: 'collaboration',
            songName: '공성전pierreblancheyonceremix',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 66,
            category: 'collaboration',
            songName: '부여성blossoremix',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 67,
            category: 'portable3',
            songName: 'enemystormdarkjunglemix',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 68,
            category: 'respect',
            songName: 'liar',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 69,
            category: 'portable1',
            songName: 'nbranger',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 70,
            category: 'respect',
            songName: '서울여자',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 71,
            category: 'collaboration',
            songName: '카트라이더크레이지아케이드버블파이터mainthemechuckremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 72,
            category: 'collaboration',
            songName: 'barbarousfunera',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 73,
            category: 'blacksquare',
            songName: 'coloursofsorrow',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 74,
            category: 'collaboration',
            songName: 'obelisque',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 75,
            category: 'respect',
            songName: 'rockstar',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 76,
            category: 'respect',
            songName: 'watchyourstep',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 77,
            category: 'clazziquai',
            songName: 'ycestyle',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 78,
            category: 'clazziquai',
            songName: '영원',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 79,
            category: 'blacksquare',
            songName: 'feverpitchgirl',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 80,
            category: 'collaboration',
            songName: 'inmyheartestiremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 81,
            category: 'portable1',
            songName: 'longvacation',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 82,
            category: 'blacksquare',
            songName: 'lovelyhands',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 83,
            category: 'respect',
            songName: 'neon1989estiremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 84,
            category: 'blacksquare',
            songName: 'readynow',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 85,
            category: 'collaboration',
            songName: 'reminiscence',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 86,
            category: 'respect',
            songName: 'uad',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 87,
            category: 'collaboration',
            songName: '연합군과제국군',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 88,
            category: 'technika2',
            songName: 'rageofdemon',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 89,
            category: 'portable1',
            songName: 'red',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 90,
            category: 'respect',
            songName: '너로피어오라',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 91,
            category: 'portable1',
            songName: 'canwetalk',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 92,
            category: 'collaboration',
            songName: 'frontline',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 93,
            category: 'portable1',
            songName: 'memoryofbeach',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 94,
            category: 'respect',
            songName: 'popstars',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 95,
            category: 'trilogy',
            songName: 'stop',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 96,
            category: 'respect',
            songName: 'voldenuit',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 97,
            category: 'technika2',
            songName: 'xlasher',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 98,
            category: 'respect',
            songName: 'alonena',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 99,
            category: 'collaboration',
            songName: 'constantmoderato',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 100,
            category: 'technika3',
            songName: 'fallininluv',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 101,
            category: 'respect',
            songName: 'gloryday',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 102,
            category: 'technika1',
            songName: 'remember',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 103,
            category: 'respect',
            songName: '염라',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 104,
            category: 'respect',
            songName: 'gloryday',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 105,
            category: 'collaboration',
            songName: 'gotmoreraves',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 106,
            category: 'emotional',
            songName: 'knowledgesystem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 107,
            category: 'technika1',
            songName: 'landscape',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 108,
            category: 'collaboration',
            songName: 'shootout',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 109,
            category: 'clazziquai',
            songName: 'inmyheart',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 110,
            category: 'collaboration',
            songName: 'axion',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 111,
            category: 'portable2',
            songName: 'midnightblood',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 112,
            category: 'portable2',
            songName: 'syriana',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 113,
            category: 'blacksquare',
            songName: 'ybsstyle',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 114,
            category: 'collaboration',
            songName: 'legacy',
            songLevel: 'sc',
            judgement: '',
          },
        ]
      ]
    }
  }
}
</script>

<style scoped>

</style>