<template>
  <div class="eight15">
    <h1>8B 15LV</h1>
    <div v-for="(difficulty, grade) in difficultyBoard" v-bind:key="grade">
      <div class="grade">
        <img class="gradeBox" :src="require(`@/assets/img/grade/${difficultyBoard.length-grade}.png`)" alt="등급">
        <div class="levelBox">
          <div class="thumbBox" v-for="thumb in difficulty" v-bind:key="thumb.id">
            <img class="sName" :src="require(`@/assets/img/thumbnails/${thumb.category}/${thumb.songName}.jpg`)" alt="썸네일">
            <img class="sLevel" :src="require(`@/assets/img/level/${thumb.songLevel}.png`)" alt="난이도">
            <img class="sBorder" :src="require(`@/assets/img/border/${thumb.category}.png`)" alt="카데고리">
            <input class="judgeBox" type="text" placeholder="-- . -- %" v-model="thumb.judgement">
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "eight15",
  data: function (){
    return{
      difficultyBoard:[
        [
          {
            id: 1,
            category: 'portable2',
            songName: 'nightmare',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 2,
            category: 'portable1',
            songName: 'roadofdeath',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 3,
            category: 'technika3',
            songName: 'xeus',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 4,
            category: 'collaboration',
            songName: 'entrance',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 5,
            category: 'blacksquare',
            songName: 'heartofwitch',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 6,
            category: 'collaboration',
            songName: 'ikazuchi',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 7,
            category: 'technika1',
            songName: 'sonofsun',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 8,
            category: 'collaboration',
            songName: 'trrricksters',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 9,
            category: 'collaboration',
            songName: '죽음의신크로우크루아흐',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 10,
            category: 'technika2',
            songName: 'd2',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 11,
            category: 'collaboration',
            songName: 'l',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 12,
            category: 'technika2',
            songName: 'rageofdemon',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 13,
            category: 'trilogy',
            songName: 'ventilator',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 14,
            category: 'collaboration',
            songName: '전설이시작된곳voidroverremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 15,
            category: 'collaboration',
            songName: '카트라이더mashupcosmographremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 16,
            category: 'respect',
            songName: 'analys',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 17,
            category: 'technika3',
            songName: 'blackswan',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 18,
            category: 'technika2',
            songName: 'dreamofwinds',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 19,
            category: 'respect',
            songName: 'glorydayjhsremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 20,
            category: 'collaboration',
            songName: 'goodnightbadluck',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 21,
            category: 'technika1',
            songName: 'landscape',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 22,
            category: 'collaboration',
            songName: 'mammal',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 23,
            category: 'technika3',
            songName: 'supernova',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 24,
            category: 'technika2',
            songName: 'thorextendedmix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 25,
            category: 'collaboration',
            songName: 'warrior',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 26,
            category: 'portable2',
            songName: 'brainstorm',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 27,
            category: 'collaboration',
            songName: 'entrance',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 28,
            category: 'blacksquare',
            songName: 'heartofwitch',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 29,
            category: 'respect',
            songName: 'nevermind',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 30,
            category: 'technika1',
            songName: 'sonofsunextendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 31,
            category: 'portable2',
            songName: 'stalker',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 32,
            category: 'collaboration',
            songName: 'blackmind',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 33,
            category: 'collaboration',
            songName: 'ember',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 34,
            category: 'collaboration',
            songName: 'helix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 35,
            category: 'portable1',
            songName: 'lighthouse',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 36,
            category: 'portable3',
            songName: 'outlawreborn',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 37,
            category: 'portable1',
            songName: 'paraq',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 38,
            category: 'technika1',
            songName: 'thor',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 39,
            category: 'collaboration',
            songName: 'anima',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 40,
            category: 'technika2',
            songName: 'd2',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 41,
            category: 'portable3',
            songName: 'enemystormdarkjunglemix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 42,
            category: 'respect',
            songName: 'nbrangervirginforce',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 43,
            category: 'collaboration',
            songName: 'thewheeltotheright',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 44,
            category: 'respect',
            songName: 'wereallgonnadie',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 45,
            category: 'technika1',
            songName: 'beyondthefuture',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 46,
            category: 'respect',
            songName: 'danceofthedead',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 47,
            category: 'technika3',
            songName: 'feelmabeat',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 48,
            category: 'blacksquare',
            songName: 'fermion',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 49,
            category: 'technika1',
            songName: 'fury',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 50,
            category: 'collaboration',
            songName: 'garakutadollplay',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 51,
            category: 'respect',
            songName: 'glorydaymintormentremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 52,
            category: 'trilogy',
            songName: 'mindcontrol',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 53,
            category: 'collaboration',
            songName: 'myosotis',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 54,
            category: 'portable3',
            songName: 'nbrangernonstopremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 55,
            category: 'respect',
            songName: 'remainsofdoom',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 56,
            category: 'technika3',
            songName: 'showdown',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 57,
            category: 'collaboration',
            songName: '죽음의신크로우크루아흐',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 58,
            category: 'technika3',
            songName: 'bambooonbamboo',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 59,
            category: 'collaboration',
            songName: 'ember',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 60,
            category: 'collaboration',
            songName: 'garakutadollplay',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 61,
            category: 'collaboration',
            songName: 'ikazuchi',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 62,
            category: 'collaboration',
            songName: 'mammal',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 63,
            category: 'respect',
            songName: 'mulch',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 64,
            category: 'collaboration',
            songName: 'ouroborostwinstrokeoftheend',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 65,
            category: 'technika2',
            songName: 'rageofdemon',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 66,
            category: 'respect',
            songName: '너로피어오라',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 67,
            category: 'collaboration',
            songName: 'barbarousfunera',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 68,
            category: 'portable3',
            songName: 'leavemealone',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 69,
            category: 'emotional',
            songName: 'realoverdrive',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 70,
            category: 'technika3',
            songName: 'rightback',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 71,
            category: 'portable1',
            songName: 'rockordie',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 72,
            category: 'collaboration',
            songName: '카트라이더mashupcosmographremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 73,
            category: 'blacksquare',
            songName: 'fermion',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 74,
            category: 'blacksquare',
            songName: 'inmydream',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 75,
            category: 'collaboration',
            songName: 'l',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 76,
            category: 'technika1',
            songName: 'sonofsun',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 77,
            category: 'collaboration',
            songName: 'trrricksters',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 78,
            category: 'collaboration',
            songName: '광명의루루라바다',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 79,
            category: 'collaboration',
            songName: '최종무곡',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 80,
            category: 'portable1',
            songName: 'astrofight',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 81,
            category: 'vextension',
            songName: 'attack',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 82,
            category: 'portable1',
            songName: 'hamsin',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 83,
            category: 'respect',
            songName: 'killerbee',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 84,
            category: 'emotional',
            songName: 'knowledgesystem',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 85,
            category: 'vextension',
            songName: 'neverdie',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 86,
            category: 'collaboration',
            songName: 'obelisque',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 87,
            category: 'portable1',
            songName: 'oblivionrockinnightstyle',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 88,
            category: 'technika3',
            songName: 'outofctrl',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 89,
            category: 'portable1',
            songName: 'revenge',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 90,
            category: 'portable2',
            songName: 'rollingontheduck',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 91,
            category: 'technika2',
            songName: 'theguilty',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 92,
            category: 'portable1',
            songName: 'sin',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 93,
            category: 'emotional',
            songName: 'superlovely',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 94,
            category: 'portable2',
            songName: 'brainstorm',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 95,
            category: 'blacksquare',
            songName: 'cyphergate',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 96,
            category: 'clazziquai',
            songName: 'electronics',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 97,
            category: 'collaboration',
            songName: 'holyordersbejustorbedead',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 98,
            category: 'portable2',
            songName: 'minus3',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 99,
            category: 'portable2',
            songName: 'nbpower',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 100,
            category: 'portable2',
            songName: 'nbrangersreturns',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 101,
            category: 'portable2',
            songName: 'nightmare',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 102,
            category: 'respect',
            songName: 'binaryworld',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 103,
            category: 'vextension',
            songName: 'fightnightfeatcalyae',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 104,
            category: 'vextension',
            songName: 'rememberme',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 105,
            category: 'portable2',
            songName: 'yourownmiracle',
            songLevel: 'sc',
            judgement: '',
          },
        ]
      ]
    }
  }
}
</script>

<style scoped>

</style>