<template>
  <div class="five13">
    <h1>5B 13LV</h1>
    <div v-for="(difficulty, grade) in difficultyBoard" v-bind:key="grade">
      <div class="grade">
        <img class="gradeBox" :src="require(`@/assets/img/grade/${difficultyBoard.length-grade}.png`)" alt="등급">
        <div class="levelBox">
          <div class="thumbBox" v-for="thumb in difficulty" v-bind:key="thumb.id">
            <img class="sName" :src="require(`@/assets/img/thumbnails/${thumb.category}/${thumb.songName}.jpg`)" alt="썸네일">
            <img class="sLevel" :src="require(`@/assets/img/level/${thumb.songLevel}.png`)" alt="난이도">
            <img class="sBorder" :src="require(`@/assets/img/border/${thumb.category}.png`)" alt="카데고리">
            <input class="judgeBox" type="text" placeholder="-- . -- %" v-model="thumb.judgement">
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "five13",
  created() {
    let id = 1
    for(let i = 0; i < this.difficultyBoard.length; i++){
      for(let j = 0; j < this.difficultyBoard[i].length; j++)
        this.difficultyBoard[i][j].id = id++
    }
  },
  data: function (){
    return{
      difficultyBoard:[
        [
          {
            id: 0,
            category: 'portable1',
            songName: 'roadofdeath',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 1,
            category: 'technika3',
            songName: 'emblem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 2,
            category: 'portable1',
            songName: 'hamsin',
            songLevel: 'mx',
            judgement: '',
          },
        ],
        [
          {
            id: 3,
            category: 'collaboration',
            songName: 'raytuning',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 4,
            category: 'respect',
            songName: 'wereallgonnadie',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 5,
            category: 'portable2',
            songName: '태권부리',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 6,
            category: 'clazziquai',
            songName: 'electronics',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 7,
            category: 'blacksquare',
            songName: 'graveconsequence',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 8,
            category: 'collaboration',
            songName: 'helix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 9,
            category: 'trilogy',
            songName: 'stop',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 10,
            category: 'collaboration',
            songName: '안아줘',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 11,
            category: 'portable3',
            songName: 'luvflowfunkyhousemix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 12,
            category: 'portable2',
            songName: 'negativenature',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 13,
            category: 'technika2',
            songName: 'sweetdream',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 14,
            category: 'portable2',
            songName: 'brainstorm',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 15,
            category: 'collaboration',
            songName: '카트라이더mashuppure100remix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 16,
            category: 'technika3',
            songName: 'blackswan',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 17,
            category: 'portable2',
            songName: 'nbpower',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 18,
            category: 'portable1',
            songName: 'oblivionrockinnightstyle',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 19,
            category: 'respect',
            songName: 'risingthesonic',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 20,
            category: 'portable2',
            songName: 'whiteblue',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 21,
            category: 'technika3',
            songName: '유령',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 22,
            category: 'blacksquare',
            songName: 'readynow',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 23,
            category: 'collaboration',
            songName: '부여성blossoremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 24,
            category: 'technika2',
            songName: 'airwave',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 25,
            category: 'respect',
            songName: 'binaryworld',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 26,
            category: 'collaboration',
            songName: 'gotmoreraves',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 27,
            category: 'vextension',
            songName: 'lisrim',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 28,
            category: 'vextension',
            songName: 'rememberme',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 29,
            category: 'collaboration',
            songName: 'starttheadventuresophiremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 30,
            category: 'clazziquai',
            songName: 'theclearbluesky',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 31,
            category: 'collaboration',
            songName: 'theraindropflowerjamjamremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 32,
            category: 'vextension',
            songName: 'wonderlot777',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 33,
            category: 'respect',
            songName: '서울여자',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 34,
            category: 'portable2',
            songName: 'braveitout',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 35,
            category: 'technika2',
            songName: 'novamrfunkyremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 36,
            category: 'portable3',
            songName: 'raisemeup',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 37,
            category: 'collaboration',
            songName: '전설이시작된곳voidroverremix',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 38,
            category: 'technika2',
            songName: 'lacampanellanurave',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 39,
            category: 'portable1',
            songName: 'lemonade',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 40,
            category: 'collaboration',
            songName: '소년모험가sinaremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 41,
            category: 'technika3',
            songName: 'ad2222extendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 42,
            category: 'portable1',
            songName: 'canwetalk',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 43,
            category: 'technika2',
            songName: 'd2',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 44,
            category: 'technika3',
            songName: 'darkprism',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 45,
            category: 'technika2',
            songName: 'dreamofwinds',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 46,
            category: 'respect',
            songName: 'glorydayjhsremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 47,
            category: 'respect',
            songName: 'gridsystem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 48,
            category: 'portable3',
            songName: 'hanzup',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 49,
            category: 'portable3',
            songName: 'therainmaker',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 50,
            category: 'respect',
            songName: 'blackcat',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 51,
            category: 'portable3',
            songName: 'mellowdfantasy',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 52,
            category: 'collaboration',
            songName: 'ninepointeight',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 53,
            category: 'collaboration',
            songName: 'univus',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 54,
            category: 'portable3',
            songName: 'yoursmile',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 55,
            category: 'respect',
            songName: '너로피어오라',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 56,
            category: 'collaboration',
            songName: 'anima',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 57,
            category: 'portable2',
            songName: 'midnightblood',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 58,
            category: 'portable1',
            songName: 'red',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 59,
            category: 'collaboration',
            songName: 'trrricksters',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 60,
            category: 'collaboration',
            songName: '광명의루루라바다',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 61,
            category: 'collaboration',
            songName: '최종무곡',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 62,
            category: 'portable3',
            songName: 'desperadonuskoolmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 63,
            category: 'vextension',
            songName: 'fightnightfeatcalyae',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 64,
            category: 'blacksquare',
            songName: 'keystotheworld',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 65,
            category: 'emotional',
            songName: 'knowledgesystem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 66,
            category: 'collaboration',
            songName: 'obelisque',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 67,
            category: 'collaboration',
            songName: 'oldgold',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 68,
            category: 'respect',
            songName: 'relationagainestisremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 69,
            category: 'technika3',
            songName: 'rightback',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 70,
            category: 'collaboration',
            songName: 'shootout',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 72,
            category: 'portable3',
            songName: 'supersonicmrfunkydirtyplanetremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 73,
            category: 'vextension',
            songName: 'vilerequiem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 74,
            category: 'collaboration',
            songName: 'constantmoderato',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 75,
            category: 'respect',
            songName: 'doyouwantit',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 76,
            category: 'respect',
            songName: 'endofmythology',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 77,
            category: 'clazziquai',
            songName: 'lovercestyle',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 78,
            category: 'technika2',
            songName: 'puzzler',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 79,
            category: 'technika1',
            songName: 'remember',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 80,
            category: 'blacksquare',
            songName: 'ybsstyle',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 81,
            category: 'collaboration',
            songName: 'entrance',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 82,
            category: 'portable2',
            songName: 'nightmare',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 83,
            category: 'collaboration',
            songName: 'ouroborostwinstrokeoftheend',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 84,
            category: 'collaboration',
            songName: 'thewheeltotheright',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 85,
            category: 'portable3',
            songName: 'leavemealone',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 86,
            category: 'portable1',
            songName: 'rayofilluminati',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 87,
            category: 'trilogy',
            songName: 'talktalk',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 88,
            category: 'technika2',
            songName: 'cozyquilt',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 89,
            category: 'portable1',
            songName: 'longvacation',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 90,
            category: 'vextension',
            songName: 'maharajahfenomenoedition',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 91,
            category: 'technika3',
            songName: 'egg',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 92,
            category: 'collaboration',
            songName: 'lesparfumsdelamour',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 93,
            category: 'portable2',
            songName: 'miles',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 94,
            category: 'technika2',
            songName: 'theguilty',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 95,
            category: 'technika2',
            songName: 'xlasher',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 96,
            category: 'clazziquai',
            songName: '내게로와',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 97,
            category: 'portable2',
            songName: 'memoirs',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 98,
            category: 'collaboration',
            songName: 'utopiosphere',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 99,
            category: 'collaboration',
            songName: 'angelicsphere',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 100,
            category: 'blacksquare',
            songName: '고백꽃늑대part2',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 101,
            category: 'portable1',
            songName: 'memoryofbeach',
            songLevel: 'sc',
            judgement: '',
          },
        ]
      ]
    }
  }
}
</script>

<style scoped>

</style>