<template>
  <div class="five14">
    <h1>5B 14LV</h1>
    <div v-for="(difficulty, grade) in difficultyBoard" v-bind:key="grade">
      <div class="grade">
        <img class="gradeBox" :src="require(`@/assets/img/grade/${difficultyBoard.length-grade}.png`)" alt="등급">
        <div class="levelBox">
          <div class="thumbBox" v-for="thumb in difficulty" v-bind:key="thumb.id">
            <img class="sName" :src="require(`@/assets/img/thumbnails/${thumb.category}/${thumb.songName}.jpg`)" alt="썸네일">
            <img class="sLevel" :src="require(`@/assets/img/level/${thumb.songLevel}.png`)" alt="난이도">
            <img class="sBorder" :src="require(`@/assets/img/border/${thumb.category}.png`)" alt="카데고리">
            <input class="judgeBox" type="text" placeholder="-- . -- %" v-model="thumb.judgement">
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "five14",
  data: function (){
    return{
      difficultyBoard:[
        [
          {
            id: 1,
            category: 'portable1',
            songName: 'oblivion',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 3,
            category: 'portable1',
            songName: 'minimallife',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 2,
            category: 'technika2',
            songName: 'lacampanellanurave',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 4,
            category: 'portable1',
            songName: 'revenge',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 5,
            category: 'technika3',
            songName: 'showdown',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 16,
            category: 'trilogy',
            songName: 'theone',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 6,
            category: 'technika3',
            songName: 'feelmabeat',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 7,
            category: 'blacksquare',
            songName: 'fermion',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 8,
            category: 'blacksquare',
            songName: 'inmydream',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 9,
            category: 'trilogy',
            songName: 'ventilator',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 10,
            category: 'collaboration',
            songName: '연합군과제국군',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 11,
            category: 'technika2',
            songName: 'beeutiful',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 12,
            category: 'portable2',
            songName: 'dreamofyou',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 13,
            category: 'portable1',
            songName: 'extremez4',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 20,
            category: 'collaboration',
            songName: 'itsmywarnow',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 22,
            category: 'portable1',
            songName: 'masai',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 14,
            category: 'technika3',
            songName: 'signalize',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 15,
            category: 'collaboration',
            songName: 'starttheadventuresophiremix',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 17,
            category: 'clazziquai',
            songName: 'darkenvy',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 18,
            category: 'collaboration',
            songName: 'marrymenightmare',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 19,
            category: 'respect',
            songName: 'alice',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 70,
            category: 'collaboration',
            songName: 'axion',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 21,
            category: 'technika1',
            songName: 'landscape',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 23,
            category: 'portable2',
            songName: 'messitup',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 24,
            category: 'technika1',
            songName: 'supersonic',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 25,
            category: 'technika2',
            songName: 'theguilty',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 26,
            category: 'collaboration',
            songName: 'theraindropflowerjamjamremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 27,
            category: 'respect',
            songName: 'watchyourstep',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 71,
            category: 'collaboration',
            songName: '카트라이더mashupcosmographremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 72,
            category: 'blacksquare',
            songName: 'beatudown',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 73,
            category: 'respect',
            songName: 'danceofthedead',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 74,
            category: 'portable3',
            songName: 'goneastray',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 75,
            category: 'collaboration',
            songName: 'goodnightbadluck',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 76,
            category: 'collaboration',
            songName: 'l',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 77,
            category: 'respect',
            songName: 'mulch',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 78,
            category: 'portable3',
            songName: 'nbrangernonstopremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 79,
            category: 'collaboration',
            songName: '최종무곡',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 80,
            category: 'portable3',
            songName: 'break',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 81,
            category: 'technika3',
            songName: 'kungfurider',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 82,
            category: 'portable3',
            songName: 'masaielectrohousemix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 83,
            category: 'portable2',
            songName: 'midnightblood',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 84,
            category: 'portable1',
            songName: 'neversay',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 85,
            category: 'portable1',
            songName: 'outlaw',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 86,
            category: 'portable3',
            songName: 'supersonicmrfunkydirtyplanetremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 87,
            category: 'emotional',
            songName: 'urbannight',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 88,
            category: 'vextension',
            songName: 'welcometothespacefeatjisun',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 28,
            category: 'collaboration',
            songName: '카트라이더크레이지아케이드버블파이터mainthemechuckremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 89,
            category: 'respect',
            songName: 'glorydaymintormentremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 29,
            category: 'vextension',
            songName: 'kensei',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 30,
            category: 'respect',
            songName: 'remainsofdoom',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 31,
            category: 'portable2',
            songName: 'rollingontheduck',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 32,
            category: 'technika1',
            songName: 'sonofsun',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 33,
            category: 'technika3',
            songName: 'egg',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 34,
            category: 'respect',
            songName: 'fareastprincess',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 35,
            category: 'collaboration',
            songName: 'frontline',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 36,
            category: 'clazziquai',
            songName: 'hereinthemoment',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 37,
            category: 'blacksquare',
            songName: 'loverbsstyle',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 38,
            category: 'collaboration',
            songName: 'obelisque',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 39,
            category: 'emotional',
            songName: 'realoverdrive',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 40,
            category: 'collaboration',
            songName: 'ververg',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 41,
            category: 'collaboration',
            songName: '공성전pierreblancheyonceremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 42,
            category: 'blacksquare',
            songName: 'airwaveextendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 43,
            category: 'collaboration',
            songName: 'itsmywarnow',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 44,
            category: 'vextension',
            songName: 'neverdie',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 45,
            category: 'portable3',
            songName: 'outlawreborn',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 46,
            category: 'emotional',
            songName: 'spaceofsoul',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 47,
            category: 'technika1',
            songName: 'thor',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 48,
            category: 'clazziquai',
            songName: '너에게',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 50,
            category: 'portable1',
            songName: 'ftr',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 51,
            category: 'portable1',
            songName: 'futurism',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 52,
            category: 'collaboration',
            songName: 'magnolia',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 53,
            category: 'collaboration',
            songName: 'satisfiction',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 54,
            category: 'trilogy',
            songName: 'yocreoquesilivehouseversion',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 55,
            category: 'technika3',
            songName: 'xeus',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 62,
            category: 'portable1',
            songName: 'ai',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 49,
            category: 'portable1',
            songName: 'cnp',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 56,
            category: 'portable1',
            songName: 'endofthemoonlight',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 57,
            category: 'trilogy',
            songName: 'stop',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 58,
            category: 'vextension',
            songName: 'blackgold',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 59,
            category: 'collaboration',
            songName: 'blackmind',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 60,
            category: 'respect',
            songName: 'dontdie',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 61,
            category: 'portable2',
            songName: 'seeker',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 64,
            category: 'respect',
            songName: 'risingthesonic',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 65,
            category: 'portable2',
            songName: 'syriana',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 69,
            category: 'portable1',
            songName: 'triplezoe',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 66,
            category: 'technika3',
            songName: 'ad2222extendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 67,
            category: 'portable2',
            songName: 'cherokee',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 63,
            category: 'portable2',
            songName: 'divineservice',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 68,
            category: 'respect',
            songName: 'getjinxed',
            songLevel: 'sc',
            judgement: '',
          },
        ]
      ]
    }
  }
}
</script>

<style scoped>

</style>