<template>
  <div class="six13">
    <h1>6B 13LV</h1>
    <div v-for="(difficulty, grade) in difficultyBoard" v-bind:key="grade">
      <div class="grade">
        <img class="gradeBox" :src="require(`@/assets/img/grade/${difficultyBoard.length-grade}.png`)" alt="등급">
        <div class="levelBox">
          <div class="thumbBox" v-for="thumb in difficulty" v-bind:key="thumb.id">
            <img class="sName" :src="require(`@/assets/img/thumbnails/${thumb.category}/${thumb.songName}.jpg`)" alt="썸네일">
            <img class="sLevel" :src="require(`@/assets/img/level/${thumb.songLevel}.png`)" alt="난이도">
            <img class="sBorder" :src="require(`@/assets/img/border/${thumb.category}.png`)" alt="카데고리">
            <input class="judgeBox" type="text" placeholder="-- . -- %" v-model="thumb.judgement">
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "six13",
  data: function (){
    return{
      difficultyBoard:[
        [
          {
            id: 1,
            category: 'collaboration',
            songName: 'ikazuchi',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 2,
            category: 'portable2',
            songName: 'nightmare',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 3,
            category: 'respect',
            songName: 'wereallgonnadie',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 4,
            category: 'portable1',
            songName: 'oblivionrockinnightstyle',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 5,
            category: 'portable2',
            songName: 'anotherday',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 6,
            category: 'blacksquare',
            songName: 'coloursofsorrow',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 7,
            category: 'collaboration',
            songName: 'lachelnthecityofdreams',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 8,
            category: 'technika2',
            songName: 'lacampanellanurave',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 9,
            category: 'portable2',
            songName: 'midnightblood',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 10,
            category: 'portable1',
            songName: 'outlaw',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 11,
            category: 'portable2',
            songName: 'whiteblue',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 12,
            category: 'trilogy',
            songName: 'catchyou',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 13,
            category: 'portable3',
            songName: 'everything',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 14,
            category: 'portable2',
            songName: 'fallenangel',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 15,
            category: 'clazziquai',
            songName: 'lovemode',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 16,
            category: 'blacksquare',
            songName: 'lovelyhands',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 17,
            category: 'technika3',
            songName: 'nowanewday',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 18,
            category: 'technika2',
            songName: 'sweetdream',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 19,
            category: 'collaboration',
            songName: 'ouroborostwinstrokeoftheend',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 20,
            category: 'collaboration',
            songName: 'raytuning',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 21,
            category: 'portable1',
            songName: 'ai',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 22,
            category: 'collaboration',
            songName: 'codenamezero',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 23,
            category: 'blacksquare',
            songName: 'cyphergate',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 24,
            category: 'collaboration',
            songName: 'marionette',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 25,
            category: 'respect',
            songName: 'nevermind',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 26,
            category: 'portable2',
            songName: 'seeker',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 27,
            category: 'technika3',
            songName: 'supernova',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 28,
            category: 'portable3',
            songName: 'therainmaker',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 29,
            category: 'vextension',
            songName: 'doit',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 30,
            category: 'vextension',
            songName: 'fancynight',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 31,
            category: 'respect',
            songName: 'gloryday',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 32,
            category: 'clazziquai',
            songName: 'inmyheart',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 33,
            category: 'collaboration',
            songName: 'inmyheartestiremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 34,
            category: 'respect',
            songName: 'runninggirl',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 35,
            category: 'technika1',
            songName: 'sweetshiningshootingstar',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 36,
            category: 'technika3',
            songName: 'emblem',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 37,
            category: 'collaboration',
            songName: '카트라이더mashuppure100remix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 38,
            category: 'collaboration',
            songName: '카트라이더크레이지아케이드버블파이터mainthemechuckremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 39,
            category: 'collaboration',
            songName: 'cyberozar',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 40,
            category: 'portable2',
            songName: 'getout',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 41,
            category: 'collaboration',
            songName: 'helix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 42,
            category: 'respect',
            songName: 'killerbee',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 43,
            category: 'respect',
            songName: 'kungbrother',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 44,
            category: 'portable3',
            songName: 'nbrangernonstopremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 45,
            category: 'emotional',
            songName: 'urbannight',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 46,
            category: 'respect',
            songName: '서울여자',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 47,
            category: 'respect',
            songName: 'blackcat',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 48,
            category: 'portable1',
            songName: 'chronobreakers',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 49,
            category: 'clazziquai',
            songName: 'coastaltempo',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 50,
            category: 'technika2',
            songName: 'cozyquilt',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 51,
            category: 'technika1',
            songName: 'dearmylady',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 52,
            category: 'respect',
            songName: 'endofmythology',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 53,
            category: 'technika1',
            songName: 'iwantyou',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 54,
            category: 'respect',
            songName: 'neon1989estiremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 55,
            category: 'portable3',
            songName: 'raisemeup',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 56,
            category: 'collaboration',
            songName: 'reminiscence',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 57,
            category: 'technika2',
            songName: 'sayitfromyourheart',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 58,
            category: 'respect',
            songName: 'shadowflower',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 59,
            category: 'collaboration',
            songName: '전설이시작된곳voidroverremix',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 60,
            category: 'collaboration',
            songName: 'anima',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 61,
            category: 'portable1',
            songName: 'astrofight',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 62,
            category: 'technika3',
            songName: 'outofctrl',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 63,
            category: 'emotional',
            songName: 'realoverdrive',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 64,
            category: 'technika3',
            songName: 'ad2222',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 65,
            category: 'technika3',
            songName: 'ad2222extendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 66,
            category: 'vextension',
            songName: 'attack',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 67,
            category: 'technika2',
            songName: 'beeutiful',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 68,
            category: 'portable2',
            songName: 'cherokee',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 69,
            category: 'clazziquai',
            songName: 'darkenvy',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 70,
            category: 'portable1',
            songName: 'dreadnought',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 71,
            category: 'respect',
            songName: 'glorydayjhsremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 72,
            category: 'emotional',
            songName: 'knowledgesystem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 73,
            category: 'collaboration',
            songName: 'marrymenightmare',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 74,
            category: 'portable2',
            songName: 'minus3',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 75,
            category: 'portable1',
            songName: 'nbranger',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 76,
            category: 'portable2',
            songName: 'nbrangersreturns',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 77,
            category: 'portable1',
            songName: 'rayofilluminati',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 78,
            category: 'collaboration',
            songName: 'oldgold',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 79,
            category: 'portable2',
            songName: 'syriana',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 80,
            category: 'respect',
            songName: 'theobliterator',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 81,
            category: 'collaboration',
            songName: 'theraindropflowerjamjamremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 82,
            category: 'technika2',
            songName: 'xlasher',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 83,
            category: 'trilogy',
            songName: 'zet',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 84,
            category: 'emotional',
            songName: 'feel',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 85,
            category: 'portable1',
            songName: 'sunnysidedeepnsoulmix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 86,
            category: 'portable3',
            songName: 'yoursmile',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 87,
            category: 'respect',
            songName: '너로피어오라',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 88,
            category: 'respect',
            songName: 'binaryworld',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 89,
            category: 'portable2',
            songName: 'braveitout',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 90,
            category: 'technika2',
            songName: 'dualstrikers',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 91,
            category: 'vextension',
            songName: 'fightnightfeatcalyae',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 92,
            category: 'respect',
            songName: 'glorydaymintormentremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 93,
            category: 'respect',
            songName: 'gridsystem',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 94,
            category: 'portable2',
            songName: 'nbpower',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 95,
            category: 'respect',
            songName: 'rutingothwildelectroremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 96,
            category: 'clazziquai',
            songName: 'theclearbluesky',
            songLevel: 'mx',
            judgement: '',
          },
        ],
        [
          {
            id: 97,
            category: 'collaboration',
            songName: '최종무곡',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 98,
            category: 'technika3',
            songName: 'angel',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 99,
            category: 'collaboration',
            songName: 'angelicsphere',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 100,
            category: 'collaboration',
            songName: 'axion',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 101,
            category: 'portable2',
            songName: 'miles',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 102,
            category: 'collaboration',
            songName: 'myosotis',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 103,
            category: 'respect',
            songName: 'quixotic',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 104,
            category: 'respect',
            songName: 'royalclown',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 105,
            category: 'trilogy',
            songName: 'talktalk',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 106,
            category: 'vextension',
            songName: 'vilerequiem',
            songLevel: 'mx',
            judgement: '',
          },
        ],
        [
          {
            id: 107,
            category: 'respect',
            songName: '염라',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 108,
            category: 'technika3',
            songName: 'eggextendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 109,
            category: 'collaboration',
            songName: 'ember',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 110,
            category: 'vextension',
            songName: 'lisrim',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 111,
            category: 'collaboration',
            songName: 'magnolia',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 112,
            category: 'vextension',
            songName: 'rememberme',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 113,
            category: 'respect',
            songName: 'risingthesonic',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 114,
            category: 'collaboration',
            songName: 'shootout',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 115,
            category: 'respect',
            songName: 'sadmachine',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 116,
            category: 'respect',
            songName: 'boom',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 117,
            category: 'respect',
            songName: 'liar',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 118,
            category: 'collaboration',
            songName: 'legacy',
            songLevel: 'sc',
            judgement: '',
          },
        ]
      ]
    }
  }
}
</script>

<style scoped>

</style>