<template>
  <div class="six14">
    <h1>6B 14LV</h1>
    <div v-for="(difficulty, grade) in difficultyBoard" v-bind:key="grade">
      <div class="grade">
        <img class="gradeBox" :src="require(`@/assets/img/grade/${difficultyBoard.length-grade}.png`)" alt="등급">
        <div class="levelBox">
          <div class="thumbBox" v-for="thumb in difficulty" v-bind:key="thumb.id">
            <img class="sName" :src="require(`@/assets/img/thumbnails/${thumb.category}/${thumb.songName}.jpg`)" alt="썸네일">
            <img class="sLevel" :src="require(`@/assets/img/level/${thumb.songLevel}.png`)" alt="난이도">
            <img class="sBorder" :src="require(`@/assets/img/border/${thumb.category}.png`)" alt="카데고리">
            <input class="judgeBox" type="text" placeholder="-- . -- %" v-model="thumb.judgement">
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "six14",
  data: function (){
    return{
      difficultyBoard:[
        [
          {
            id: 1,
            category: 'collaboration',
            songName: 'helix',
            songLevel: 'sc',
            judgement: '',
          }
        ],
        [
          {
            id: 2,
            category: 'respect',
            songName: 'entertheuniverse',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 3,
            category: 'portable2',
            songName: 'messitup',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 4,
            category: 'portable2',
            songName: 'stalker',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 5,
            category: 'trilogy',
            songName: 'theone',
            songLevel: 'sc',
            judgement: '',
          }
        ],
        [
          {
            id: 6,
            category: 'portable2',
            songName: 'brainstorm',
            songLevel: 'hd',
            judgement: '',
          },
          {
            id: 7,
            category: 'portable1',
            songName: 'sin',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 8,
            category: 'portable1',
            songName: 'sinthelastscene',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 9,
            category: 'portable2',
            songName: 'chainofgravity',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 10,
            category: 'portable2',
            songName: 'dreamofyou',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 11,
            category: 'respect',
            songName: 'iwantyou반짝반짝sunshine',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 12,
            category: 'portable2',
            songName: 'negativenature',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 13,
            category: 'portable3',
            songName: 'therainmaker',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 14,
            category: 'trilogy',
            songName: 'yocreoquesilivehouseversion',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 15,
            category: 'blacksquare',
            songName: 'airwaveextendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 16,
            category: 'portable1',
            songName: 'astrofight',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 17,
            category: 'collaboration',
            songName: 'goodnightbadluck',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 18,
            category: 'technika1',
            songName: 'sonofsun',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 19,
            category: 'technika1',
            songName: 'sonofsunextendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 20,
            category: 'trilogy',
            songName: 'ventilator',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 21,
            category: 'collaboration',
            songName: '카트라이더mashuppure100remix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 22,
            category: 'collaboration',
            songName: 'apparition',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 23,
            category: 'portable1',
            songName: 'fear',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 24,
            category: 'respect',
            songName: 'flyaway',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 25,
            category: 'portable2',
            songName: 'goodbye',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 26,
            category: 'portable2',
            songName: 'higher',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 27,
            category: 'portable2',
            songName: 'miles',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 28,
            category: 'portable1',
            songName: 'outlaw',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 29,
            category: 'technika3',
            songName: 'signalize',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 30,
            category: 'respect',
            songName: 'waitingforyou',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 31,
            category: 'respect',
            songName: 'watchyourstep',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 32,
            category: 'portable3',
            songName: 'zetmrfunkyremix',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 33,
            category: 'respect',
            songName: 'analys',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 34,
            category: 'blacksquare',
            songName: 'fermion',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 35,
            category: 'portable1',
            songName: 'hamsin',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 36,
            category: 'collaboration',
            songName: 'mammal',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 37,
            category: 'trilogy',
            songName: 'mindcontrol',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 38,
            category: 'respect',
            songName: 'nbrangervirginforce',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 39,
            category: 'collaboration',
            songName: '최종무곡',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 40,
            category: 'respect',
            songName: 'bulletwanted',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 41,
            category: 'technika3',
            songName: 'feelmabeat',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 42,
            category: 'vextension',
            songName: 'nanairo',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 43,
            category: 'collaboration',
            songName: 'obelisque',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 44,
            category: 'collaboration',
            songName: 'raytuning',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 45,
            category: 'portable2',
            songName: 'smokyquartz',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 46,
            category: 'portable3',
            songName: 'supersonicmrfunkydirtyplanetremix',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 51,
            category: 'collaboration',
            songName: '공성전pierreblancheyonceremix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 52,
            category: 'collaboration',
            songName: 'blackmind',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 53,
            category: 'respect',
            songName: 'mulch',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 54,
            category: 'portable2',
            songName: 'rollingontheduck',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 55,
            category: 'emotional',
            songName: 'spaceofsoul',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 56,
            category: 'technika1',
            songName: 'thor',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 57,
            category: 'technika2',
            songName: 'thorextendedmix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 58,
            category: 'collaboration',
            songName: 'warrior',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 59,
            category: 'technika3',
            songName: 'xeus',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 60,
            category: 'clazziquai',
            songName: 'creator',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 61,
            category: 'respect',
            songName: 'doyouwantit',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 62,
            category: 'portable2',
            songName: 'getontop',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 63,
            category: 'technika3',
            songName: 'kungfurider',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 64,
            category: 'technika2',
            songName: 'monoxide',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 65,
            category: 'trilogy',
            songName: 'nbgirls',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 66,
            category: 'blacksquare',
            songName: 'pdm',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 67,
            category: 'respect',
            songName: 'relationagainestisremix',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 68,
            category: 'technika1',
            songName: 'shoreline',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 69,
            category: 'trilogy',
            songName: 'someday',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 70,
            category: 'portable2',
            songName: 'syriana',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 71,
            category: 'collaboration',
            songName: 'tayberrscollapsedparadise',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 72,
            category: 'clazziquai',
            songName: 'theclearbluesky',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 73,
            category: 'technika2',
            songName: 'airwave',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 74,
            category: 'blacksquare',
            songName: 'beatudown',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 75,
            category: 'portable1',
            songName: 'blythe',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 76,
            category: 'technika3',
            songName: 'darkprism',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 77,
            category: 'respect',
            songName: 'dontdie',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 78,
            category: 'blacksquare',
            songName: 'heartofwitch',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 79,
            category: 'blacksquare',
            songName: 'inmydream',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 80,
            category: 'vextension',
            songName: 'neverdie',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 81,
            category: 'vextension',
            songName: 'maharajahfenomenoedition',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 82,
            category: 'portable1',
            songName: 'onethelove',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 83,
            category: 'portable2',
            songName: 'plasticmethod',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 84,
            category: 'portable2',
            songName: '태권부리',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 85,
            category: 'collaboration',
            songName: 'breakaspell',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 86,
            category: 'respect',
            songName: 'danceofthedead',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 87,
            category: 'portable3',
            songName: 'enemystormdarkjunglemix',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 88,
            category: 'portable3',
            songName: 'goneastray',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 89,
            category: 'collaboration',
            songName: 'itsmywarnow',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 90,
            category: 'vextension',
            songName: 'kensei',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 91,
            category: 'portable3',
            songName: 'leavemealone',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 92,
            category: 'portable2',
            songName: 'myalias',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 93,
            category: 'technika3',
            songName: 'rightback',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 94,
            category: 'collaboration',
            songName: 'satisfiction',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 95,
            category: 'technika3',
            songName: 'showdown',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 96,
            category: 'portable3',
            songName: 'becomemyself',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 97,
            category: 'portable2',
            songName: 'cherokee',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 98,
            category: 'portable1',
            songName: 'endofthemoonlight',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 99,
            category: 'clazziquai',
            songName: 'flea',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 100,
            category: 'collaboration',
            songName: 'magnolia',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 101,
            category: 'portable1',
            songName: 'triplezoe',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 102,
            category: 'vextension',
            songName: 'blackgold',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 103,
            category: 'collaboration',
            songName: 'conflict',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 104,
            category: 'technika3',
            songName: 'feelmabeat',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 105,
            category: 'portable3',
            songName: 'outlawreborn',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 106,
            category: 'vextension',
            songName: 'wonderlot777',
            songLevel: 'mx',
            judgement: '',
          },
          {
            id: 107,
            category: 'clazziquai',
            songName: 'color',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 108,
            category: 'portable1',
            songName: 'jupiterdriving',
            songLevel: 'sc',
            judgement: '',
          },
        ],
        [
          {
            id: 109,
            category: 'clazziquai',
            songName: '영원',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 110,
            category: 'portable2',
            songName: 'divineservice',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 111,
            category: 'respect',
            songName: 'getjinxed',
            songLevel: 'sc',
            judgement: '',
          },
          {
            id: 108,
            category: 'respect',
            songName: 'popstars',
            songLevel: 'sc',
            judgement: '',
          },
        ]
      ]
    }
  }
}
</script>

<style scoped>

</style>